version: '3.8'

services:
  # PostgreSQL Container
  postgres:
    image: public.ecr.aws/m6q2o4x8/postgre:latest
    container_name: todo_postgre
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pp123456789
      POSTGRES_DB: techprotodo
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Node.js Backend Container
  backend:
    image: public.ecr.aws/m6q2o4x8/nodejs:latest
    container_name: todo_backend
    environment:
      SERVER_PORT: 5000
      DB_USER: postgres
      DB_PASSWORD: Pp123456789
      DB_NAME: techprotodo
      DB_HOST: todo_postgre
      DB_PORT: 5432
    ports:
      - 5000:5000
    depends_on:
      - postgres
    command: bash -c "npm install && npm run start"


  # React Frontend Container
  frontend:
    image: public.ecr.aws/m6q2o4x8/react:latest
    container_name: todo_frontend
    environment:
      REACT_APP_BASE_URL: http://44.221.60.24:5000/
    ports:
      - 3000:3000
    command: bash -c "npm install && npm start"
      
volumes:
  postgres_data:
networks:
  jenkinsproject: